# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - soulder_joint
    - upper_arm_joint
    - elbow_joint
    - lower_arm_joint
    - wrist_joint
    - finger_joint
default_q: [
    0.0,-0.0002,-0.0,-0.0007,0.0,-0.0
]

acceleration_limits: [
   10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:
    - {name: gripper_joint, rule: fixed, value: -0.0}

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  shoulder_link:
    - "center": [0.0, -0.03, 0.025]
      "radius": 0.02
    - "center": [0.0, 0.0, 0.025]
      "radius": 0.02
    - "center": [0.0, -0.03, 0.025]
      "radius": 0.02
  upper_arm_link:
    - "center": [0.0, -0.0, 0.05]
      "radius": 0.02
  elbow_link:
    - "center": [0.0, 0.0, 0.03]
      "radius": 0.01
    - "center": [0.0, 0.02, 0.03]
      "radius": 0.01
    - "center": [0.0, -0.02, 0.03]
      "radius": 0.01
  lower_arm_link:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.06]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.08]
      "radius": 0.01
  wrist_link:
    - "center": [0.0, -0.006, 0.045]
      "radius": 0.014
    - "center": [0.0, -0.027, 0.045]
      "radius": 0.014
  gripper_link:
    - "center": [0.0, -0.01, -0.033]
      "radius": 0.013
  finger_link:
    - "center": [0.0, 0.023, 0.002]
      "radius": 0.008
